In [1]:
import numpy as np
import pandas as pd
import math
from scipy.stats import norm
from scipy.optimize import fsolve
from numpy.linalg import inv
import scipy.integrate
from numpy.linalg import inv

In [2]:
a1=np.zeros((4,4))
a1[0][0]=1
a2=np.zeros((4,4))
a2[1][1]=1
a3=np.zeros((4,4))
a3[2][2]=1
a4=np.zeros((4,4))
a4[3][3]=1
a12=np.zeros((4,4))
a12[0][1]=1
a13=np.zeros((4,4))
a13[0][2]=1
a14=np.zeros((4,4))
a14[0][3]=1
a23=np.zeros((4,4))
a23[1][2]=1
a24=np.zeros((4,4))
a24[1][3]=1
a34=np.zeros((4,4))
a34[2][3]=1
b1=a1[0]
b2=a2[1]
b3=a3[2]
b4=a4[3]

In [3]:
N=1000
alpha=0.05
z=norm.ppf(1-alpha/2)
F_inverse=[]
H_inverse=[]
theta_MLE=[]
while len(F_inverse)<N:
    n=2000
    Q=[]
    U=np.random.rand(4,4)/10
    for i in range(n):
        Q.append((i+1)**0.5*np.dot(U,U.transpose()))

    mu=[0,0,0,0]
    sigma=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
    X=[]
    for i in range(n):
        X.append(np.random.multivariate_normal(mu,sigma+Q[i]))
    
    
    def ML(paramlist):
        mu1=paramlist[0]
        mu2=paramlist[1]
        mu3=paramlist[2]
        mu4=paramlist[3]
        sigma1=paramlist[4]
        sigma2=paramlist[5]
        sigma3=paramlist[6]
        sigma4=paramlist[7]
    
        s1=np.zeros((4,4))
        s2=np.zeros((4,4))
        
        for i in range(n):
            s1=s1+np.diag(np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),[mu1,mu2,mu3,mu4])-np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),X[i]))
            s2=s2+inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i])-np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),np.matmul(np.outer((X[i]-[mu1,mu2,mu3,mu4]),(X[i]-[mu1,mu2,mu3,mu4])),inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i])))
        return s1[0][0],s1[1][1],s1[2][2],s1[3][3],s2[0][0],s2[1][1],s2[2][2],s2[3][3]


    theta_hat=fsolve(ML,[0,0,0,0,1,1,1,1])
    mu_hat=theta_hat[0:4]
    sigma_hat=np.array([[theta_hat[4],0,0,0],[0,theta_hat[5],0,0],
                        [0,0,theta_hat[6],0],[0,0,0,theta_hat[7]]])

    fmu11=0
    fmu22=0
    fmu33=0
    fmu44=0
    fmu12=0
    fmu13=0
    fmu14=0
    fmu23=0
    fmu24=0
    fmu34=0
    fsigma11=0
    fsigma22=0
    fsigma33=0
    fsigma44=0
    fsigma12=0
    fsigma13=0
    fsigma14=0
    fsigma23=0
    fsigma24=0
    fsigma34=0
    hmu=0
    hsigma11=0
    hsigma22=0
    hsigma33=0
    hsigma44=0
    hsigma12=0
    hsigma13=0
    hsigma14=0
    hsigma23=0
    hsigma24=0
    hsigma34=0
    hsigmamu1=0
    hsigmamu2=0
    hsigmamu3=0
    hsigmamu4=0
    for i in range(n):
        fmu11=fmu11+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b1)
        fmu22=fmu22+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b2)
        fmu33=fmu33+1/n*np.matmul(np.matmul(np.transpose(b3),inv(sigma_hat+Q[i])),b3)
        fmu44=fmu44+1/n*np.matmul(np.matmul(np.transpose(b4),inv(sigma_hat+Q[i])),b4)
        fmu12=fmu12+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b2)
        fmu13=fmu13+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b3)
        fmu14=fmu14+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b4)
        fmu23=fmu23+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b3)
        fmu24=fmu24+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b4)
        fmu34=fmu34+1/n*np.matmul(np.matmul(np.transpose(b3),inv(sigma_hat+Q[i])),b4)

        fsigma11=fsigma11+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a1)
        fsigma22=fsigma22+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a2)
        fsigma33=fsigma33+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*a3)
        fsigma44=fsigma44+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])*a4)
        fsigma12=fsigma12+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a2)
        fsigma13=fsigma13+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a3)
        fsigma14=fsigma14+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a4)
        fsigma23=fsigma23+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a3)
        fsigma24=fsigma24+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a4)
        fsigma34=fsigma34+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*a4)
    
        hmu=hmu+1/n*inv(sigma_hat+Q[i])
    
        hsigma11=hsigma11-1/n*(1/2)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])
        hsigma22=hsigma22-1/n*(1/2)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])
        hsigma33=hsigma33-1/n*(1/2)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])
        hsigma44=hsigma44-1/n*(1/2)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
        1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])
    
        hsigmamu1=hsigmamu1+1/n*np.matmul(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
        hsigmamu2=hsigmamu2+1/n*np.matmul(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
        hsigmamu3=hsigmamu3+1/n*np.matmul(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
        hsigmamu4=hsigmamu4+1/n*np.matmul(inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
    
    fmu=np.array([[fmu11,fmu12,fmu13,fmu14],[fmu12,fmu22,fmu23,fmu24],
                 [fmu13,fmu23,fmu33,fmu34],[fmu14,fmu24,fmu34,fmu44]])

    fsigma=np.array([[fsigma11,fsigma12,fsigma13,fsigma14],[fsigma12,fsigma22,fsigma23,fsigma24],
                 [fsigma13,fsigma23,fsigma33,fsigma34],[fsigma14,fsigma24,fsigma34,fsigma44]])

    F=np.block([[fmu,np.zeros((4,4))],[np.zeros((4,4)),fsigma]]) 
    
    hsigma=np.array([[hsigma11[0][0],hsigma11[1][1],hsigma11[2][2],hsigma11[3][3]],[hsigma11[1][1],hsigma22[1][1],hsigma22[2][2],hsigma22[3][3]],
                     [hsigma11[2][2],hsigma22[2][2],hsigma33[2][2],hsigma33[3][3]],[hsigma11[3][3],hsigma22[3][3],hsigma33[3][3],hsigma44[3][3]]])
   
    hsigmamu=np.array([hsigmamu1,hsigmamu2,hsigmamu3,hsigmamu4])
    H=np.block([[hmu,hsigmamu],[hsigmamu,hsigma]])
    
    if max(theta_hat)<100:
        F_inverse.append(inv(F))
        H_inverse.append(inv(H))
        theta_MLE.append(theta_hat)
    
    print(len(F_inverse))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [4]:
mu1_MLE=[]
mu2_MLE=[]
mu3_MLE=[]
mu4_MLE=[]
sigma1_MLE=[]
sigma2_MLE=[]
sigma3_MLE=[]
sigma4_MLE=[]
for i in range(len(theta_MLE)):
    mu1_MLE.append(theta_MLE[i][0])
    mu2_MLE.append(theta_MLE[i][1])
    mu3_MLE.append(theta_MLE[i][2])
    mu4_MLE.append(theta_MLE[i][3])
    sigma1_MLE.append(theta_MLE[i][4])
    sigma2_MLE.append(theta_MLE[i][5])
    sigma3_MLE.append(theta_MLE[i][6])
    sigma4_MLE.append(theta_MLE[i][7])

In [5]:
data = np.array([mu1_MLE,mu2_MLE,mu3_MLE,mu4_MLE,sigma1_MLE,sigma2_MLE,sigma3_MLE,sigma4_MLE])
V=n*np.cov(data)

In [6]:
from numpy import linalg as LA
dF=[]
dH=[]
for i in range(len(F_inverse)):
    dF.append(LA.norm(F_inverse[i]-V))
    dH.append(LA.norm(H_inverse[i]-V))
mF=np.argsort(dF)[len(dF)//2]
mH=np.argsort(dH)[len(dH)//2]

In [7]:
V

array([[ 1.3470925 ,  0.26222542,  0.28701861,  0.26021325, -0.05046913,
        -0.06850871,  0.07150224, -0.00328604],
       [ 0.26222542,  1.44108677,  0.27611193,  0.26906528, -0.03939389,
         0.02930664,  0.10966281, -0.01166048],
       [ 0.28701861,  0.27611193,  1.4570467 ,  0.37147224,  0.00752032,
        -0.05764837, -0.00445654,  0.07375677],
       [ 0.26021325,  0.26906528,  0.37147224,  1.40170013, -0.07688005,
        -0.01407073,  0.07109277,  0.01824425],
       [-0.05046913, -0.03939389,  0.00752032, -0.07688005,  3.03937751,
        -0.14725397, -0.24485309, -0.09658868],
       [-0.06850871,  0.02930664, -0.05764837, -0.01407073, -0.14725397,
         2.88061571, -0.07267128,  0.05024782],
       [ 0.07150224,  0.10966281, -0.00445654,  0.07109277, -0.24485309,
        -0.07267128,  2.72365639,  0.0300482 ],
       [-0.00328604, -0.01166048,  0.07375677,  0.01824425, -0.09658868,
         0.05024782,  0.0300482 ,  2.890695  ]])

In [8]:
F_inverse[mF]

array([[1.19745385, 0.24372468, 0.37425557, 0.27784511, 0.        ,
        0.        , 0.        , 0.        ],
       [0.24372468, 1.26293739, 0.37381173, 0.27078193, 0.        ,
        0.        , 0.        , 0.        ],
       [0.37425557, 0.37381173, 1.58301516, 0.45233602, 0.        ,
        0.        , 0.        , 0.        ],
       [0.27784511, 0.27078193, 0.45233602, 1.32618707, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.28519717,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        2.57691807, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 3.42301059, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 2.65880063]])

In [9]:
H_inverse[mH]

array([[ 1.15752390e+00,  1.61665959e-01,  2.62648073e-01,
         3.11950195e-01, -1.13632174e-02,  3.93282302e-04,
        -2.61584860e-03, -2.97534495e-03],
       [ 1.61665959e-01,  1.39253243e+00,  1.74984576e-01,
         2.80887225e-01, -1.58704751e-03,  3.38759231e-03,
        -1.74276229e-03, -2.67906992e-03],
       [ 2.62648073e-01,  1.74984576e-01,  1.47526592e+00,
         5.30306813e-01, -2.57837193e-03,  4.25682298e-04,
        -1.46929397e-02, -5.05800516e-03],
       [ 3.11950195e-01,  2.80887225e-01,  5.30306813e-01,
         1.68500866e+00, -3.06236257e-03,  6.83310051e-04,
        -5.28160104e-03, -1.60714181e-02],
       [-1.13632174e-02, -1.58704751e-03, -2.57837193e-03,
        -3.06236257e-03,  2.03065442e+00, -3.86078618e-06,
         2.56793455e-05,  2.92084607e-05],
       [ 3.93282302e-04,  3.38759231e-03,  4.25682298e-04,
         6.83310051e-04, -3.86078618e-06,  3.25518047e+00,
        -4.23959114e-06, -6.51733238e-06],
       [-2.61584860e-03, -1.742762

In [10]:
gh11=[]
gf11=[]
gh22=[]
gf22=[]
gh33=[]
gf33=[]
gh44=[]
gf44=[]
gh55=[]
gf55=[]
gh66=[]
gf66=[]
gh77=[]
gf77=[]
gh88=[]
gf88=[]
for i in range(len(F_inverse)):
    gh11.append(2*norm.cdf(z*(H_inverse[i][0][0]/V[0][0])**0.5)-1)
    gf11.append(2*norm.cdf(z*(F_inverse[i][0][0]/V[0][0])**0.5)-1)
    gh22.append(2*norm.cdf(z*(H_inverse[i][1][1]/V[1][1])**0.5)-1)
    gf22.append(2*norm.cdf(z*(F_inverse[i][1][1]/V[1][1])**0.5)-1)
    gh33.append(2*norm.cdf(z*(H_inverse[i][2][2]/V[2][2])**0.5)-1)
    gf33.append(2*norm.cdf(z*(F_inverse[i][2][2]/V[2][2])**0.5)-1)
    gh44.append(2*norm.cdf(z*(H_inverse[i][3][3]/V[3][3])**0.5)-1)
    gf44.append(2*norm.cdf(z*(F_inverse[i][3][3]/V[3][3])**0.5)-1)
    gh55.append(2*norm.cdf(z*(H_inverse[i][4][4]/V[4][4])**0.5)-1)
    gf55.append(2*norm.cdf(z*(F_inverse[i][4][4]/V[4][4])**0.5)-1)
    gh66.append(2*norm.cdf(z*(H_inverse[i][5][5]/V[5][5])**0.5)-1)
    gf66.append(2*norm.cdf(z*(F_inverse[i][5][5]/V[5][5])**0.5)-1)
    gh77.append(2*norm.cdf(z*(H_inverse[i][6][6]/V[6][6])**0.5)-1)
    gf77.append(2*norm.cdf(z*(F_inverse[i][6][6]/V[6][6])**0.5)-1)
    gh88.append(2*norm.cdf(z*(H_inverse[i][7][7]/V[7][7])**0.5)-1)
    gf88.append(2*norm.cdf(z*(F_inverse[i][7][7]/V[7][7])**0.5)-1)

In [11]:
MSEh11=np.mean((gh11-np.asarray(0.95))**2)
MSEf11=np.mean((gf11-np.asarray(0.95))**2)
print(MSEh11)
print(MSEf11)
print(MSEh11/MSEf11)

0.0001854133929464229
0.00018540907414214402
1.0000232933813993


In [12]:
MSEh22=np.mean((gh22-np.asarray(0.95))**2)
MSEf22=np.mean((gf22-np.asarray(0.95))**2)
print(MSEh22)
print(MSEf22)
print(MSEh22/MSEf22)

0.00029428744953698447
0.00029430756375490853
0.9999316557900605


In [13]:
MSEh33=np.mean((gh33-np.asarray(0.95))**2)
MSEf33=np.mean((gf33-np.asarray(0.95))**2)
print(MSEh33)
print(MSEf33)
print(MSEh33/MSEf33)

0.00033223176209926645
0.0003322534141665725
0.9999348326717414


In [14]:
MSEh44=np.mean((gh44-np.asarray(0.95))**2)
MSEf44=np.mean((gf44-np.asarray(0.95))**2)
print(MSEh44)
print(MSEf44)
print(MSEh44/MSEf44)

0.00022236119830403627
0.00022236835130187946
0.9999678326623312


In [15]:
MSEh55=np.mean((gh55-np.asarray(0.95))**2)
MSEf55=np.mean((gf55-np.asarray(0.95))**2)
print(MSEh55)
print(MSEf55)
print(MSEh55/MSEf55)

0.001335563233367488
0.0004099542809372423
3.2578345817345964


In [16]:
MSEh66=np.mean((gh66-np.asarray(0.95))**2)
MSEf66=np.mean((gf66-np.asarray(0.95))**2)
print(MSEh66)
print(MSEf66)
print(MSEh66/MSEf66)

0.0009642837023194679
0.00034493161305621266
2.7955793723155233


In [17]:
MSEh77=np.mean((gh77-np.asarray(0.95))**2)
MSEf77=np.mean((gf77-np.asarray(0.95))**2)
print(MSEh77)
print(MSEf77)
print(MSEh77/MSEf77)

0.000596122344690366
0.00038457798202117856
1.5500688353436152


In [18]:
MSEh88=np.mean((gh88-np.asarray(0.95))**2)
MSEf88=np.mean((gf88-np.asarray(0.95))**2)
print(MSEh88)
print(MSEf88)
print(MSEh88/MSEf88)

0.0009998797133077785
0.0003393658317799534
2.946318160739605
