In [405]:
import numpy as np
import pandas as pd
import math
from scipy.stats import norm
from scipy.optimize import fsolve
from numpy.linalg import inv
import scipy.integrate

In [406]:
n=50
Q=[]

In [407]:
U=np.random.rand(4,4)
U

array([[0.96030204, 0.72856101, 0.78835018, 0.01704618],
       [0.2697762 , 0.23978557, 0.38146812, 0.68125919],
       [0.12770817, 0.88788085, 0.13105754, 0.98561835],
       [0.76081893, 0.61013186, 0.68242059, 0.45509055]])

In [408]:
for i in range(n):
    Q.append((i+1)**0.5*np.dot(U,U.transpose()))

In [409]:
mu=[0,0,0,0]
sigma=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [410]:
X=[]
for i in range(n):
    X.append(np.random.multivariate_normal(mu,sigma+Q[i]))

In [411]:
from numpy.linalg import inv

In [439]:
 def ML(paramlist):
    mu1=paramlist[0]
    mu2=paramlist[1]
    mu3=paramlist[2]
    mu4=paramlist[3]
    sigma1=paramlist[4]
    sigma2=paramlist[5]
    sigma3=paramlist[6]
    sigma4=paramlist[7]
    
    s1=np.zeros((4,4))
    s2=np.zeros((4,4))
        
    for i in range(n):
        s1=s1+np.diag(np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),[mu1,mu2,mu3,mu4])-np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),X[i]))
        s2=s2+inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i])-np.matmul(inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i]),np.matmul(np.outer((X[i]-[mu1,mu2,mu3,mu4]),(X[i]-[mu1,mu2,mu3,mu4])),inv(np.diag([sigma1,sigma2,sigma3,sigma4])+Q[i])))
    return s1[0][0],s1[1][1],s1[2][2],s1[3][3],s2[0][0],s2[1][1],s2[2][2],s2[3][3]

In [440]:
theta_hat=fsolve(ML,[0,0,0,0,1,1,1,1])
theta_hat

array([0.03453586, 0.11134712, 0.29931846, 0.07930058, 1.37036645,
       0.78866411, 0.7637776 , 0.74111034])

In [414]:
mu_hat=theta_hat[0:4]
mu_hat

array([-0.06611272,  0.06646504,  0.23811125, -0.00638896])

In [415]:
sigma_hat=np.array([[theta_hat[4],0,0,0],[0,theta_hat[5],0,0],
                    [0,0,theta_hat[6],0],[0,0,0,theta_hat[7]]])
sigma_hat

array([[1.41222322, 0.        , 0.        , 0.        ],
       [0.        , 1.03674148, 0.        , 0.        ],
       [0.        , 0.        , 0.24453592, 0.        ],
       [0.        , 0.        , 0.        , 0.69970858]])

In [416]:
a1=np.zeros((4,4))
a1[0][0]=1
a2=np.zeros((4,4))
a2[1][1]=1
a3=np.zeros((4,4))
a3[2][2]=1
a4=np.zeros((4,4))
a4[3][3]=1
a12=np.zeros((4,4))
a12[0][1]=1
a13=np.zeros((4,4))
a13[0][2]=1
a14=np.zeros((4,4))
a14[0][3]=1
a23=np.zeros((4,4))
a23[1][2]=1
a24=np.zeros((4,4))
a24[1][3]=1
a34=np.zeros((4,4))
a34[2][3]=1
print(a1)
print(a2)
print(a3)
print(a4)
print(a12)
print(a13)
print(a14)
print(a23)
print(a24)
print(a34)
b1=a1[0]
b2=a2[1]
b3=a3[2]
b4=a4[3]

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [417]:
#Fisher Information Matrix
fmu11=0
fmu22=0
fmu33=0
fmu44=0
fmu12=0
fmu13=0
fmu14=0
fmu23=0
fmu24=0
fmu34=0
for i in range(n):
    fmu11=fmu11+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b1)
    fmu22=fmu22+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b2)
    fmu33=fmu33+1/n*np.matmul(np.matmul(np.transpose(b3),inv(sigma_hat+Q[i])),b3)
    fmu44=fmu44+1/n*np.matmul(np.matmul(np.transpose(b4),inv(sigma_hat+Q[i])),b4)
    fmu12=fmu12+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b2)
    fmu13=fmu13+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b3)
    fmu14=fmu14+1/n*np.matmul(np.matmul(np.transpose(b1),inv(sigma_hat+Q[i])),b4)
    fmu23=fmu23+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b3)
    fmu24=fmu24+1/n*np.matmul(np.matmul(np.transpose(b2),inv(sigma_hat+Q[i])),b4)
    fmu34=fmu34+1/n*np.matmul(np.matmul(np.transpose(b3),inv(sigma_hat+Q[i])),b4)
# cross part of mu and sigma is zero in Fisher Information matrix


In [418]:
fmu=np.array([[fmu11,fmu12,fmu13,fmu14],[fmu12,fmu22,fmu23,fmu24],
                 [fmu13,fmu23,fmu33,fmu34],[fmu14,fmu24,fmu34,fmu44]])
fmu

array([[ 0.34158107,  0.05686433,  0.05553347, -0.39227263],
       [ 0.05686433,  0.60675783, -0.18986102, -0.24210768],
       [ 0.05553347, -0.18986102,  0.30406222, -0.15221204],
       [-0.39227263, -0.24210768, -0.15221204,  0.73703454]])

In [419]:
fsigma11=0
fsigma22=0
fsigma33=0
fsigma44=0
fsigma12=0
fsigma13=0
fsigma14=0
fsigma23=0
fsigma24=0
fsigma34=0
for i in range(n):
    fsigma11=fsigma11+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a1)
    fsigma22=fsigma22+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a2)
    fsigma33=fsigma33+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*a3)
    fsigma44=fsigma44+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])*a4)
    fsigma12=fsigma12+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a2)
    fsigma13=fsigma13+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a3)
    fsigma14=fsigma14+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*a4)
    fsigma23=fsigma23+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a3)
    fsigma24=fsigma24+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*a4)
    fsigma34=fsigma34+1/n*(1/2)*np.trace(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*a4)

In [420]:
fsigma=np.array([[fsigma11,fsigma12,fsigma13,fsigma14],[fsigma12,fsigma22,fsigma23,fsigma24],
                 [fsigma13,fsigma23,fsigma33,fsigma34],[fsigma14,fsigma24,fsigma34,fsigma44]])
fsigma

array([[0.05879248, 0.        , 0.        , 0.        ],
       [0.        , 0.18641633, 0.        , 0.        ],
       [0.        , 0.        , 0.0530936 , 0.        ],
       [0.        , 0.        , 0.        , 0.27229119]])

In [421]:
F=np.block([[fmu,np.zeros((4,4))],[np.zeros((4,4)),fsigma]])
F

array([[ 0.34158107,  0.05686433,  0.05553347, -0.39227263,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.05686433,  0.60675783, -0.18986102, -0.24210768,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.05553347, -0.18986102,  0.30406222, -0.15221204,  0.        ,
         0.        ,  0.        ,  0.        ],
       [-0.39227263, -0.24210768, -0.15221204,  0.73703454,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.05879248,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.18641633,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.0530936 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.27229119]])

In [422]:
# Hessian Matrix
hmu=0
for i in range(n):
    hmu=hmu+1/n*inv(sigma_hat+Q[i])
hmu

array([[ 0.34158107,  0.05686433,  0.05553347, -0.39227263],
       [ 0.05686433,  0.60675783, -0.18986102, -0.24210768],
       [ 0.05553347, -0.18986102,  0.30406222, -0.15221204],
       [-0.39227263, -0.24210768, -0.15221204,  0.73703454]])

In [423]:
hsigma11=0
hsigma22=0
hsigma33=0
hsigma44=0
hsigma12=0
hsigma13=0
hsigma14=0
hsigma23=0
hsigma24=0
hsigma34=0
for i in range(n):
    hsigma11=hsigma11-1/n*(1/2)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i])
    hsigma22=hsigma22-1/n*(1/2)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i])
    hsigma33=hsigma33-1/n*(1/2)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i])
    hsigma44=hsigma44-1/n*(1/2)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])+ \
    1/n*(1/2)*inv(sigma_hat+Q[i])*np.outer(X[i]-mu_hat,X[i]-mu_hat)*inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i])

In [424]:
hsigma11

array([[0.50369033, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [425]:
hsigma22

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.69836991, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [426]:
hsigma33

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.18552536, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [427]:
hsigma44

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 3.73473788]])

In [428]:
hsigma=np.array([[hsigma11[0][0],hsigma11[1][1],hsigma11[2][2],hsigma11[3][3]],[hsigma11[1][1],hsigma22[1][1],hsigma22[2][2],hsigma22[3][3]],
                 [hsigma11[2][2],hsigma22[2][2],hsigma33[2][2],hsigma33[3][3]],[hsigma11[3][3],hsigma22[3][3],hsigma33[3][3],hsigma44[3][3]]])

In [429]:
hsigma

array([[0.50369033, 0.        , 0.        , 0.        ],
       [0.        , 0.69836991, 0.        , 0.        ],
       [0.        , 0.        , 0.18552536, 0.        ],
       [0.        , 0.        , 0.        , 3.73473788]])

In [430]:
hsigmamu1=0
hsigmamu2=0
hsigmamu3=0
hsigmamu4=0
for i in range(n):
    hsigmamu1=hsigmamu1+1/n*np.matmul(inv(sigma_hat+Q[i])*a1*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
    hsigmamu2=hsigmamu2+1/n*np.matmul(inv(sigma_hat+Q[i])*a2*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
    hsigmamu3=hsigmamu3+1/n*np.matmul(inv(sigma_hat+Q[i])*a3*inv(sigma_hat+Q[i]),(X[i]-mu_hat))
    hsigmamu4=hsigmamu4+1/n*np.matmul(inv(sigma_hat+Q[i])*a4*inv(sigma_hat+Q[i]),(X[i]-mu_hat))

In [431]:
hsigmamu1

array([0.02100372, 0.        , 0.        , 0.        ])

In [432]:
hsigmamu2

array([0.       , 0.0236271, 0.       , 0.       ])

In [433]:
hsigmamu=np.array([hsigmamu1,hsigmamu2,hsigmamu3,hsigmamu4])

In [434]:
hsigmamu

array([[0.02100372, 0.        , 0.        , 0.        ],
       [0.        , 0.0236271 , 0.        , 0.        ],
       [0.        , 0.        , 0.00219583, 0.        ],
       [0.        , 0.        , 0.        , 0.09853779]])

In [435]:
H=np.block([[hmu,hsigmamu],[hsigmamu,hsigma]])

In [436]:
H

array([[ 3.41581068e-01,  5.68643326e-02,  5.55334700e-02,
        -3.92272632e-01,  2.10037170e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 5.68643326e-02,  6.06757833e-01, -1.89861021e-01,
        -2.42107681e-01,  0.00000000e+00,  2.36271049e-02,
         0.00000000e+00,  0.00000000e+00],
       [ 5.55334700e-02, -1.89861021e-01,  3.04062220e-01,
        -1.52212041e-01,  0.00000000e+00,  0.00000000e+00,
         2.19582629e-03,  0.00000000e+00],
       [-3.92272632e-01, -2.42107681e-01, -1.52212041e-01,
         7.37034540e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  9.85377917e-02],
       [ 2.10037170e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.03690326e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.36271049e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  6.98369909e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.000000