In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.optimize import fsolve
from numpy.linalg import inv
from scipy.stats import norm

In [2]:
N=1000
alpha=0.05
z=norm.ppf(1-alpha/2)


In [3]:
f_inverse11=[]
f_inverse22=[]
h_inverse11=[]
h_inverse22=[]
mu_MLE=[]
sigma_square_MLE=[]
F_inverse=[]
H_inverse=[]
while len(f_inverse22)<N:
    n=5000
    q=[]
    X=[]
    for i in range(n):
        q.append(0.1*(i+1)%10)
    for j in range(n):
        X.append(np.random.normal(10,(10+q[j])**0.5))

    def ML(paramlist):
        mu_hat,sigma_hat_square=paramlist[0],paramlist[1]
        s1=0
        s2=0
        for i in range(n):
            s1=s1-(X[i]-mu_hat)/(sigma_hat_square+q[i])
            s2=s2+(1/(sigma_hat_square+q[i]))/2-((X[i]-mu_hat)**2/(sigma_hat_square+q[i])**2)/2
        return s1,s2

    s=fsolve(ML,[10,10])
    mu=s[0]
    sigma_square=s[1]
    
    if sigma_square<100 and sigma_square>0:
        mu_MLE.append(mu)
        sigma_square_MLE.append(sigma_square)
        f11=0
        f22=0
        h22=0
        h11=0
        h12=0
        for i in range(n):
            f22=f22+(1/(2*n))/(sigma_square+q[i])**2
            f11=f11+(1/n)/(sigma_square+q[i])
            h11=h11+(1/n)/(sigma_square+q[i])
            h12=h12+(X[i]-mu)/(n*(sigma_square+q[i])**2)
            h22=h22-(1/(2*n))/(sigma_square+q[i])**2+(X[i]-mu)**2/(n*(sigma_square+q[i])**3)
        
        f_inverse11.append(1/f11)
        f_inverse22.append(1/f22)
        h_inverse11.append(h22/(h11*h22-h12**2))
        h_inverse22.append(h11/(h11*h22-h12**2))
        H=[[h11,h12],[h12,h22]]
        F=[[f11,0],[0,f22]]
        F_inverse.append(inv(F))
        H_inverse.append(inv(H))
    else:
        continue
    print(len(f_inverse22))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [4]:
ff=0
hh=0
for i in range(N):
    ff=ff+F_inverse[i]
    hh=hh+H_inverse[i]

In [5]:
V=np.cov(mu_MLE,sigma_square_MLE)*n

In [6]:
V

array([[ 13.43261956,   1.82922236],
       [  1.82922236, 426.24285881]])

In [7]:
Vn1=np.var(mu_MLE)*n
Vn1

13.4191869356862

In [8]:
Vn2=np.var(sigma_square_MLE)*n
Vn2

425.8166159551276

In [9]:
gh11=[]
gf11=[]
gh22=[]
gf22=[]
for i in range(len(f_inverse22)):
    gh11.append(2*norm.cdf(z*(h_inverse11[i]/Vn1)**0.5)-1)
    gf11.append(2*norm.cdf(z*(f_inverse11[i]/Vn1)**0.5)-1)
    gh22.append(2*norm.cdf(z*(h_inverse22[i]/Vn2)**0.5)-1)
    gf22.append(2*norm.cdf(z*(f_inverse22[i]/Vn2)**0.5)-1)

In [10]:
dF=[]
dH=[]
for i in range(len(F_inverse)):
    dF.append(np.linalg.norm(F_inverse[i]-V))
    dH.append(np.linalg.norm(H_inverse[i]-V))

In [11]:
dF

[41.93173425146191,
 41.613530079541704,
 3.2991220502455234,
 36.544390519169326,
 50.097873504684024,
 10.404237808642595,
 29.62298854234811,
 10.024513726060059,
 51.76870363731127,
 10.749941047039835,
 18.954870414358012,
 27.1441327111979,
 49.95914486297475,
 36.172641633858674,
 42.565727207301464,
 43.533923710299426,
 20.251566821765667,
 32.957731718856685,
 3.0455108420457724,
 22.729760567222417,
 35.18640007135595,
 16.131089827905065,
 3.425806109675313,
 24.212281049425595,
 49.86077447892646,
 37.58332166004933,
 31.283984662407548,
 47.183799434445454,
 63.255752539249094,
 32.51942361202091,
 25.255847503275433,
 13.965975116508808,
 13.557775323336056,
 72.87545798358221,
 48.683698551520756,
 23.631192845999706,
 27.89240366928078,
 36.567953483142816,
 50.988963281648935,
 36.54926839933904,
 28.423864951042464,
 12.595761820693204,
 36.270045101614265,
 34.01029244953316,
 22.55234933920373,
 11.836556362389752,
 32.240867757917506,
 10.489008984700698,
 11.7229

In [12]:
mF=np.argsort(dF)[len(dF)//2]
mH=np.argsort(dH)[len(dH)//2]

In [13]:
F_inverse[mF]

array([[ 14.3720613 ,   0.        ],
       [  0.        , 396.84353202]])

In [14]:
H_inverse[mH]

array([[ 1.43435903e+01, -9.34430640e-03],
       [-9.34430640e-03,  3.96342717e+02]])

In [15]:
MSEh22=np.mean((gh22-np.asarray(0.95))**2)
MSEf22=np.mean((gf22-np.asarray(0.95))**2)

In [16]:
MSEh11=np.mean((gh11-np.asarray(0.95))**2)
MSEf11=np.mean((gf11-np.asarray(0.95))**2)

In [17]:
MSEh22

0.00010788423851840159

In [18]:
MSEf22

0.000105896765238886

In [19]:
MSEh11/MSEf11

1.000413140082611

In [20]:
MSEh11

6.0007707951864005e-05

In [21]:
MSEf11

5.998292660061298e-05

In [22]:
MSEh22/MSEf22

1.0187680263418073